name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    name: 📤️ Publish Package
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      id-token: write
    steps:
      - name: ✅ Checkout code    
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      
      - name: 🛠️ Setup node.js      
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          
      - run: npm ci
      
      - name: 🚀 Publish Package to NPM      
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
